export default [
	{
		id: 1,
		header: "Anuj Shukla",
		type: "Pose",
		status: "Verifying",
		target: "18",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 2,
		header: "Manika Diwedi",
		type: "Situp",
		status: "Done",
		target: "22",
		limit: "F",
		reviewer: "Admin",
	},
	{
		id: 3,
		header: "Akshat Sharma",
		type: "Squats",
		status: "Done",
		target: "25",
		limit: "M",
		reviewer: "Sub-Admin",
	},
	{
		id: 4,
		header: "Ashutosh Tiwari",
		type: "Pushup",
		status: "Done",
		target: "21",
		limit: "M",
		reviewer: "Staff",
	},
	{
		id: 5,
		header: "Anushka Srivastava",
		type: "Situp",
		status: "In Process",
		target: "23",
		limit: "F",
		reviewer: "Admin",
	},
	{
		id: 6,
		header: "Dhriti Singh",
		type: "Squats",
		status: "In Process",
		target: "20",
		limit: "F",
		reviewer: "Admin",
	},
	{
		id: 7,
		header: "Anshuman Singh",
		type: "Pushup",
		status: "In Process",
		target: "24",
		limit: "M",
		reviewer: "Admin",
	},
	{
		id: 8,
		header: "Rohit Verma",
		type: "Situp",
		status: "Done",
		target: "26",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 9,
		header: "Neha Agarwal",
		type: "Squats",
		status: "Done",
		target: "19",
		limit: "F",
		reviewer: "Assign reviewer",
	},
	{
		id: 10,
		header: "Karan Malhotra",
		type: "Pushup",
		status: "Done",
		target: "28",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 11,
		header: "Simran Kaur",
		type: "Situp",
		status: "Done",
		target: "22",
		limit: "F",
		reviewer: "Assign reviewer",
	},
	{
		id: 12,
		header: "Vikram Joshi",
		type: "Squats",
		status: "Done",
		target: "27",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 13,
		header: "Aditi Mishra",
		type: "Pushup",
		status: "Done",
		target: "20",
		limit: "F",
		reviewer: "Assign reviewer",
	},
	{
		id: 14,
		header: "Saurabh Yadav",
		type: "Situp",
		status: "Done",
		target: "29",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 15,
		header: "Priya Nair",
		type: "Squats",
		status: "Done",
		target: "24",
		limit: "F",
		reviewer: "Assign reviewer",
	},
	{
		id: 16,
		header: "Rahul Mehta",
		type: "Pushup",
		status: "In Process",
		target: "23",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 17,
		header: "Shreya Banerjee",
		type: "Situp",
		status: "Done",
		target: "21",
		limit: "F",
		reviewer: "Assign reviewer",
	},
	{
		id: 18,
		header: "Arjun Kapoor",
		type: "Squats",
		status: "Done",
		target: "30",
		limit: "M",
		reviewer: "Assign reviewer",
	},
	{
		id: 19,
		header: "Meera Iyer",
		type: "Pushup",
		status: "Done",
		target: "25",
		limit: "F",
		reviewer: "Assign reviewer",
	},
	{
		id: 20,
		header: "Ritika Sharma",
		type: "Situp",
		status: "Done",
		target: "22",
		limit: "F",
		reviewer: "Assign reviewer",
	},
];
